# Generated by Django 3.2 on 2023-06-04 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20230605_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmationcode',
            name='confirmation_code',
            field=models.CharField(max_length=5),
        ),
    ]
