# Generated by Django 3.2 on 2023-06-04 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_confirmationcode_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmationcode',
            name='confirmation_code',
            field=models.CharField(max_length=5),
        ),
    ]
