# Generated by Django 3.2 on 2023-06-05 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_confirmationcode_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmationcode',
            name='username',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='confirmation_code', to='users.customuser'),
            preserve_default=False,
        ),
    ]
